# Generated by Django 5.2.1 on 2025-06-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbserver', '0002_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Members',
        ),
    ]
