# Generated by Django 5.2.1 on 2025-06-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbserver', '0003_rename_member_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
