# Generated by Django 5.2.1 on 2025-06-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbserver', '0004_rename_members_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
